### ISSUE TITLE
TwoStepAuth Sample Tutorial

### ISSUE THREAD

**Issue by zahidaziz** [MobileFirst-Platform-Developer-Center/TwoStepAuth#1]
Hi, I already configured the cloudant database, the dbName and auth variable also have been stated in the code, when I run the hybrid apps after inserting username and password, still returning ‘Database ERROR’ exception. How this is happening?

**Comment by NathanHazout** [comment]
Would you know how to run a network inspector, such as WireShark, and see what the exact response from Cloudant was?
Maybe we can find a more specific error message...

**Comment by LiorBu1** [comment]
Did you add the permissions to the generated API key?

**Comment by zahidaziz** [comment]
Yes absolutely, n I generate the api at below

**Comment by NathanHazout** [comment]
@zahidaziz Your sentence is not clear. Can you re-iterate?

**Comment by IdanAdar** [comment]
Closing due to lack of co-operation from @zahidaziz. Re-open if and when you're ready to respond.
